spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri: mongodb://localhost:27017/Journaldb
      database: Journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: moulikbhattacharya@gmail.com
    password: gvls ifxk chyc kwgw
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8089

logging:
  level:
    org:
      springframework:
        security: DEBUG

weather:
  api:
    key: 91dc01c82ca67818cb38d47a717f0e0f
